/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_subwayinfo_SubwayJNI */

#ifndef _Included_com_example_subwayinfo_SubwayJNI
#define _Included_com_example_subwayinfo_SubwayJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_subwayinfo_SubwayJNI
 * Method:    login
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_subwayinfo_SubwayJNI_login
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     com_example_subwayinfo_SubwayJNI
 * Method:    hello_jni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_subwayinfo_SubwayJNI_hello_1jni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
